<?php
/** @var \WebChemistry\Parameters\Provider $provider */
$parameters = $provider->getParameters();
$new = FALSE;
?>
<style class="tracy-debug">.nette-debug-parameters-bold { font-weight: bold !important } .nette-debug-parameters-green { color: green !important }</style>
<div class="nette-Parameters">
	<h1>Parameters</h1>

	<div class="tracy-inner">
		<table>
			<thead>
				<tr>
					<th>ID</th>
					<th>Default value</th>
					<th>Current value</th>
				</tr>
			</thead>
			<tbody>
				<?php foreach ($provider->getDefaultParameters() as $key => $value):
					$isNew = !isset($parameters[$key]);

					if ($isNew) $new = TRUE;
					?>
				<tr>
					<td class="nette-debug-parameters-bold<?php echo $isNew ? ' nette-debug-parameters-green' : '' ?>"><?php echo $key; ?></td>
					<td><?php echo \WebChemistry\Parameters\Bar\Debug::format($value); ?></td>
					<td><?php echo $isNew ? '<span class="nette-debug-parameters-green">New!</span>' : \WebChemistry\Parameters\Bar\Debug::format($parameters[$key]) ?></td>
				</tr>
				<?php endforeach; ?>
			</tbody>
		</table>
		<?php if ($new): ?>
		<a href="<?php $clone = clone $url; echo $clone->setQueryParameter('debug-import-parameters', 1) ?>">Import new variables</a>
		<?php endif; ?>
		<a href="<?php $clone = clone $url; echo $clone->setQueryParameter('debug-parameters-cache', 1) ?>">Clear cache</a>
	</div>
</div>
